global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "api-gateway"

  - job_name: "eureka-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8761"]
        labels:
          application: "eureka-server"

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          application: "auth-service"

  - job_name: "vault-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"]
        labels:
          application: "vault-service"

  - job_name: "password-generator-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8083"]
        labels:
          application: "password-generator-service"

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8085"]
        labels:
          application: "notification-service"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
